### ISSUE TITLE
Long switch code

### ISSUE THREAD

**Issue by vadumpastushok** [junkjuk/sw_course#4]
Занадто довгий код switch, потрібно якось змінити логіку

**Comment by junkjuk** [comment]
Мижливо потрібно огорнути це створення повідомлень в фабричний метод?
Чи не виглядатиме це як натягування сови на глобус?

**Comment by vadumpastushok** [comment]
Так, маєш рацію╰(*°▽°*), в нас буде занадто мало логіки в компоненті в MavLink повідомленні, але краще рознести логіку обробки в різні класи, бо так як зараз жах o((⊙﹏⊙))o.
